USE webprojectdb;
SET SESSION FOREIGN_KEY_CHECKS=0;

#한글설정
ALTER DATABASE webprojectdb CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE userinfo DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

/* Drop Tables */

DROP TABLE IF EXISTS humorcomment;
DROP TABLE IF EXISTS humorboard;
DROP TABLE IF EXISTS ITcomment;
DROP TABLE IF EXISTS ITboard;
DROP TABLE IF EXISTS userinfo;


SELECT * FROM userinfo;

#ALTER TABLE userinfo MODIFY NAME VARCHAR(30);


/* Create Tables */
CREATE TABLE userinfo
(
	id VARCHAR(15) NOT NULL,
	PASSWORD VARCHAR(15) NOT NULL,
	NAME VARCHAR(10) NOT NULL,
	email VARCHAR(30) NOT NULL,
	phone VARCHAR(15),
	PRIMARY KEY (id),
	UNIQUE (NAME),
	UNIQUE (email)
);


CREATE TABLE humorboard
(
	bidx INT NOT NULL,
	id VARCHAR(15) NOT NULL,
	NAME VARCHAR(15) NOT NULL,
	SUBJECT VARCHAR(100) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	board_ref INT NOT NULL,
	board_lev INT NOT NULL,
	board_seq INT NOT NULL,
	board_hit INT NOT NULL,
	writedate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,#timestamp DEFAULT NOW(), SYSDATE() NOT NULL,
	good INT UNSIGNED NOT NULL,
	PRIMARY KEY (bidx),
	UNIQUE (id)
);


CREATE TABLE humorcomment
(
	cidx INT NOT NULL,
	bidx INT NOT NULL,
	id VARCHAR(15) NOT NULL,
	NAME VARCHAR(15) NOT NULL,
	writedate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	content VARCHAR(100) NOT NULL,
	UNIQUE (id)
);


CREATE TABLE ITboard
(
	bidx INT NOT NULL,
	id VARCHAR(15) NOT NULL,
	NAME VARCHAR(15) NOT NULL,
	SUBJECT VARCHAR(100) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	board_ref INT NOT NULL,
	board_lev INT NOT NULL,
	board_seq INT NOT NULL,
	board_hit INT NOT NULL,
	writedate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	good INT UNSIGNED NOT NULL,
	PRIMARY KEY (bidx),
	UNIQUE (bidx)
);


CREATE TABLE ITcomment
(
	cidx INT NOT NULL,
	bidx INT NOT NULL,
	id VARCHAR(15) NOT NULL,
	NAME VARCHAR(15) NOT NULL,
	writedate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	content VARCHAR(100) NOT NULL
);




/* Create Foreign Keys */

ALTER TABLE humorcomment
	ADD FOREIGN KEY (bidx)
	REFERENCES humorboard (bidx)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ITcomment
	ADD FOREIGN KEY (bidx)
	REFERENCES ITboard (bidx)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE humorboard
	ADD FOREIGN KEY (id)
	REFERENCES userinfo (id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE humorcomment
	ADD FOREIGN KEY (id)
	REFERENCES userinfo (id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ITboard
	ADD FOREIGN KEY (id)
	REFERENCES userinfo (id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE ITcomment
	ADD FOREIGN KEY (id)
	REFERENCES userinfo (id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;

ALTER TABLE ITcomment ADD PRIMARY KEY(cidx,bidx);
ALTER TABLE humorcomment ADD PRIMARY KEY(cidx,bidx);
